[2025-04-28T22:35:22.954+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-28T22:35:22.974+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-28T22:35:12.364759+00:00 [queued]>
[2025-04-28T22:35:22.983+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-28T22:35:12.364759+00:00 [queued]>
[2025-04-28T22:35:22.984+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-28T22:35:23.000+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_stock_prices> on 2025-04-28 22:35:12.364759+00:00
[2025-04-28T22:35:23.011+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=950) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T22:35:23.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tesla_ETL', 'load_stock_prices', 'manual__2025-04-28T22:35:12.364759+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/tesla_stock_etl.py', '--cfg-path', '/tmp/tmp3jm9nqwt']
[2025-04-28T22:35:23.013+0000] {standard_task_runner.py:72} INFO - Started process 956 to run task
[2025-04-28T22:35:23.013+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask load_stock_prices
[2025-04-28T22:35:23.073+0000] {task_command.py:467} INFO - Running <TaskInstance: tesla_ETL.load_stock_prices manual__2025-04-28T22:35:12.364759+00:00 [running]> on host 5891a65dc7e9
[2025-04-28T22:35:23.166+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tesla_ETL' AIRFLOW_CTX_TASK_ID='load_stock_prices' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T22:35:12.364759+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T22:35:12.364759+00:00'
[2025-04-28T22:35:23.168+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-28T22:35:23.640+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-28T22:35:23.784+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-28T22:48:03.658+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-28T22:48:03.819+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-28T22:48:04.194+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-28T22:48:04.204+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=tesla_ETL, task_id=load_stock_prices, run_id=manual__2025-04-28T22:35:12.364759+00:00, execution_date=20250428T223512, start_date=20250428T223522, end_date=20250428T224804
[2025-04-28T22:48:05.642+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-28T22:48:05.892+0000] {taskinstance.py:3925} ERROR - Error scheduling downstream tasks. Skipping it as this is entirely optional optimisation. There might be various reasons for it, please take a look at the stack trace to figure out if the root cause can be diagnosed and fixed. See the issue https://github.com/apache/***/issues/39717 for details and an example problem. If you would like to get help in solving root cause, open discussion with all details with your managed service support or in Airflow repository.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3921, in schedule_downstream_tasks
    return TaskInstance._schedule_downstream_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 94, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3870, in _schedule_downstream_tasks
    partial_dag = task.dag.partial_subset(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2664, in partial_subset
    t.task_id: _deepcopy_task(t)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 2661, in _deepcopy_task
    return copy.deepcopy(t, memo)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 143, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1388, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 201, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle '_thread.lock' object
[2025-04-28T22:48:05.983+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
